### ISSUE TITLE
np.array() doesn't work with "0D arrays"

### ISSUE THREAD

**Issue by rhattersley** [mrocklin/dask#3]
I've been using `np.array(...)` to obtain the value of various dask arrays, but that tactic broke down when I got to 0D...
```python
>>> da.ones((3, 4), blockshape=(3, 4))[0, 0]
dask.array<x_2, shape=(), blockdims=()>
>>> da.ones((3, 4), blockshape=(3, 4))[0, 0].__array__()
1.0
>>> type(da.ones((3, 4), blockshape=(3, 4))[0, 0].__array__())
<type 'numpy.float64'>
>>> np.array(da.ones((3, 4), blockshape=(3, 4))[0, 0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: object __array__ method not producing an array
```

**Comment by rhattersley** [comment]
Perhaps I should be using the `compute()` method instead?

**Comment by mrocklin** [comment]
That would work, but what you wrote down was reasonable and should be supported.  Resolving now.

**Comment by mrocklin** [comment]
This should be resolved by https://github.com/ContinuumIO/dask/pull/77

Also, I've moved the "main" fork over to https://github.com/ContinuumIO/dask .  Issues reported there might get more visibility.

**Comment by rhattersley** [comment]
> Also, I've moved the "main" fork over to https://github.com/ContinuumIO/dask . Issues reported there might get more visibility.

Got it - thanks.
