### ISSUE TITLE
has dask been tested on win32?

### ISSUE THREAD

**Issue by phrrngtn** [mrocklin/dask#4]
I think there may be a problem with the interaction with the multiprocessing module on windows: I don't have a clean reproducible case but it seems that dask.Bag is failing with more than around 100 elements. Has any testing been done on 2.7.3 on win32?

**Comment by mrocklin** [comment]
Nope.  Haven't gotten there yet.  At some point I'll hook up a build farm for testing but until then we're dependent on user bug reports like this one.

Clean reproducable cases are welcome if they're easy to produce.

A temporary workaround would be to use the [synchronous scheduler](http://dask.readthedocs.org/en/latest/faq.html), though this would kill any multi-core parallelism that you might have had.

**Comment by phrrngtn** [comment]
thanks for the rapid response. My use-case is to do a lot of IO and data-munging in the dask task and then have a single writer iterate over the bag in batches of N elements and write those back to a database. This works just fine on Linux but on windows, I am getting this from somewhere and I suspect it is killing the workers/closing down the pool
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored

unfortunately on win32 this results in the program continuing on as if nothing happened but with only 1 batch of data written to the database. I will check into it further to see if I can locate it. I will also try the synchronous approach.

    q = m.tables['t'].insert()
    i = 0
    for b in d.take(100):
        print 'processing batch %d' % (i)
        e.execute(q, b)
        i+=100

In [23]: save_dask(d)
INSERT INTO t(id, path, x) VALUES (:id, :path, :x)
processing batch 0
processing batch 100
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
processing batch 200
processing batch 300
processing batch 400
processing batch 500
processing batch 600
processing batch 700

**Comment by phrrngtn** [comment]
I do see any problem when taking from the dask Bag 200 elements at a time with dask.async.get_sync.

    b = dask.bag.Bag.from_sequence(files)
    b.get=dask.async.get_sync

I will add back in the database persistence and see if this is merely a 'fork after opening a database connection' problem.

**Comment by phrrngtn** [comment]
This may be user error on my behalf. Let me check into it further.

**Comment by mrocklin** [comment]
Hopeful hooray for user error!

Nothing makes me happier than learning that I don't have to dive into Win32+multiprocessing interactions :)

**Comment by mrocklin** [comment]
Closing all issues on this fork.  See github.com/ContinuumIO/dask/issues for current issue tracker.
