### ISSUE TITLE
batched consumption of dask.bag 

### ISSUE THREAD

**Issue by phrrngtn** [mrocklin/dask#5]
How do you suggest consuming a dask.bag in chunks of N?  My particular use-case is writing/merging cooked output to the database (which I want to be done by a single writer to avoid unnecessary contention at the database).  I want something that iterates over the bag (ideally gathering back whatever results are available for whatever partition) and returns a block/batch that in turn is iterable to get at the items themselves. E.g.
```python
for batch in bag.batch(N):
    e.execute(q, batch)
```
 
where e is a sqlalchemy engine, q is a sqlalchemy insert query.

I have hacked together something similar with itertools.islice on top of ipython parallel.
http://ipython.org/ipython-doc/dev/parallel/asyncresult.html#map-results-are-iterable

**Comment by phrrngtn** [comment]
I should clarify that in the ipython experiment I alluded to when opening this ticket, I batched the promises and then for each batch, synchronously iterated over each element. I think the problem of iterating over the results as they become available (independent of which partition they are in) is harder.

**Comment by mrocklin** [comment]
Closing all issues on this fork.  See github.com/ContinuumIO/dask/issues for current issue tracker.
