### ISSUE TITLE
Please consider supporting ipython.parallel as a computation backend.

### ISSUE THREAD

**Issue by phrrngtn** [mrocklin/dask#6]
It would be super nice to be able to give a parallel.client.view  as the 'get' for a compute
my_array.compute(get=my_funky_view)

I think that this may help support #5 and it might also support funky topologies orthogonal to dask.

**Comment by mrocklin** [comment]
Closing all issues on this fork.  See github.com/ContinuumIO/dask/issues for current issue tracker.
