### ISSUE TITLE
how to incorporate hierarchical caching into dask?

### ISSUE THREAD

**Issue by phrrngtn** [mrocklin/dask#7]
[another feature request coming out of sidebar conversation with mrocklin]

apologies for the very half-baked suggestion. I have not worked with dask enough to identify clearly what it is that I think I want!

Use case: I want complicated dasks on immutable/append-only data to re-use previously  computed results if they are available.

_hierarchical_ means that dask sub-trees can be cached (not just the whole thing).  OK with cache busting if the scheduler/optimizer picks a different tree. Assume that cache configuration has to be tied to the scheduler (i.e. the thing that runs the dask rather than the dask itself?)

**Comment by mrocklin** [comment]
Closing all issues on this fork.  See github.com/ContinuumIO/dask/issues for current issue tracker.
